import Head from 'next/head';

const Header = () => {
    return (
        <Head>
            <title>Piush | Software Developer</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon2.ico" />
        </Head>
    );
};

export default Header;
